[phases.setup]
nixPkgs = ["chromium", "chromedriver", "libGL", "libGLU", "libdrm", "libX11", "libxkbcommon", "libxshmfence"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python main.py"
